---
title: "Group 6 Military Spending Proposal"
output: html_notebook
---

# App Title and Names of your group members

### Determinants of Military Spending

by Ozan Cetin, Jen-Yu Huang, David Leshchiner, Charlie Bollinger

# Description of the problem to be analyzed in the Shiny App

Military spending is one of the key areas each nation funds. It is a controversial topic in most nations with different factions arguing that spending should increase and others saying the opposite. Thus, Nation states’ military spending is our variable of interest. However, we want to include more factors into our analysis than raw spending totals to create a more insightful picture on the global state of national military spending. We would like to understand what demographic, economic and other factors influence military spending. This research interest and problem is going to be analyzed by our group through statistical methods, data visualization, current events, and theories discussed in social science. Our research question that drives this analysis is what factors influence military spending?

# Proposed data sources 

**Sipri:** For Military spending data

**World Development Indicators** For country level indicators related to demographics, economy, public health etc. 

**Freedom House Index** State-level democracy scores

**Polity IV** State-level democracy scores

# Concept for the Shiny App

### Overall Layout

The Shiny app will allow for several filters using several data sets. The app will initially display a map of the world with options to specify data by country or region. Each country will have a certain color meaning the higher they are ranked relative to other countries the darker shade of a color they are similar to the NYT COVID-19 map. Users will also be able to input different data sets so they could measure gross military spending or military spending as a proportion of GDP per capita, GNI per capita, population, or a similar statistic. Furthermore, users will be able to filter by year and then use gganimate to view change over time. Furthermore, the shiny app will include a table that reflects the results of the map and can be similarly filtered by country or region. Users can also generate scatter plots with linear smoothers comparing military spending to other variables such as Freedom House index scores or Global Happiness scores. Finally, users will have the option to conduct a statistical analysis of the scatter plots and other graphs which will generate key statistics to determine if the correlations are significant. 

### Data Analysis and Visualization with User Choices and Results 

**Visualization:** 

- Bubble graphs animated year by year
- Density plots of continents based on a variable
- Heat maps of variable
- Scatter Plots/Scatter Plots of variables with linear smoothers
- Map Plots

# Statistical Modeling with User Choices and Results 

Descriptive Statistics for each*
- Country
- Region
- Contient
- Common grouping (military alliance, economic bloc, historical grouping)

Regression Analysis & Diagnostics
- Model Selection (e.g. partial f-tests)
- Variable Selection (p values, AIC, VIF, BIC, Mallow's Cp, Stepwise Regression)
- Correlation analysis (adjusted R^2, R^2, p value)
- Outliers (Cook's distance, leverage)


# Allocation of Responsibilities for the team 

**David:** Visualization & Data Wrangling, Context & Background & Conclusion of models/visualizations
**Ozan:** Further Design of the App using HTML-CSS, theoretical justification of models.
**Charlie:** Statistical analysis & Data Management
**Jen-Yu:** Design of the Shiny App

# Project Steps/Schedule

**Every other week:** One hour meetup over Zoom discussing individual updates, next steps, and general brainstorm

**April 21st:** Finishing all data wrangling, manipulation, and draft visualizations

**April 23rd:** Finish all statistical analysis of data and models

**April 30th:** Finish Shiny app and relevant web elements

**May 2nd:** Practice Presentation & Finish all loose ends

**May 3:** Presentation

